name: smart_build_control_pro
description: "SmartBuild Control Pro"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  image: ^4.5.4
  image_picker:
  path_provider:
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.1
  flutter_onnxruntime: ^1.5.2
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tf_models/best_float32.tflite
